// jHipsterMicroservices/gateway/src/main/webapp/app/entities/ReferenceManagementContext/paper-collection-id/paper-collection-id.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
import { Subscription } from 'rxjs';
import { JhiEventManager } from 'ng-jhipster';
import { NgbModal } from '@ng-bootstrap/ng-bootstrap';

import { IPaperCollectionId } from 'app/shared/model/ReferenceManagementContext/paper-collection-id.model';
import { PaperCollectionIdService } from './paper-collection-id.service';
import { PaperCollectionIdDeleteDialogComponent } from './paper-collection-id-delete-dialog.component';

@Component({
  selector: 'jhi-paper-collection-id',
  templateUrl: './paper-collection-id.component.html',
})
export class PaperCollectionIdComponent implements OnInit, OnDestroy {
  paperCollectionIds?: IPaperCollectionId[];
  eventSubscriber?: Subscription;

  constructor(
    protected paperCollectionIdService: PaperCollectionIdService,
    protected eventManager: JhiEventManager,
    protected modalService: NgbModal
  ) {}

  loadAll(): void {
    this.paperCollectionIdService
      .query()
      .subscribe((res: HttpResponse<IPaperCollectionId[]>) => (this.paperCollectionIds = res.body || []));
  }

  ngOnInit(): void {
    this.loadAll();
    this.registerChangeInPaperCollectionIds();
  }

  ngOnDestroy(): void {
    if (this.eventSubscriber) {
      this.eventManager.destroy(this.eventSubscriber);
    }
  }

  trackId(index: number, item: IPaperCollectionId): number {
    // eslint-disable-next-line @typescript-eslint/no-unnecessary-type-assertion
    return item.id!;
  }

  registerChangeInPaperCollectionIds(): void {
    this.eventSubscriber = this.eventManager.subscribe('paperCollectionIdListModification', () => this.loadAll());
  }

  delete(paperCollectionId: IPaperCollectionId): void {
    const modalRef = this.modalService.open(PaperCollectionIdDeleteDialogComponent, { size: 'lg', backdrop: 'static' });
    modalRef.componentInstance.paperCollectionId = paperCollectionId;
  }
}

<div>
    <h2 id="page-heading">
        <span jhiTranslate="gatewayApp.referenceManagementContextPaperCollectionId.home.title">Paper Collection Ids</span>

        <button id="jh-create-entity" class="btn btn-primary float-right jh-create-entity create-paper-collection-id" [routerLink]="['/paper-collection-id/new']">
            <fa-icon icon="plus"></fa-icon>
            <span  jhiTranslate="gatewayApp.referenceManagementContextPaperCollectionId.home.createLabel">
            Create a new Paper Collection Id
            </span>
        </button>
    </h2>

    <jhi-alert-error></jhi-alert-error>

    <jhi-alert></jhi-alert>

    <div class="alert alert-warning" id="no-result" *ngIf="paperCollectionIds?.length === 0">
        <span jhiTranslate="gatewayApp.referenceManagementContextPaperCollectionId.home.notFound">No paperCollectionIds found</span>
    </div>

    <div class="table-responsive" id="entities" *ngIf="paperCollectionIds && paperCollectionIds.length > 0">
        <table class="table table-striped" aria-describedby="page-heading">
            <thead>
                <tr>
                    <th scope="col" ><span jhiTranslate="global.field.id">ID</span></th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                <tr *ngFor="let paperCollectionId of paperCollectionIds ;trackBy: trackId">
                    <td><a [routerLink]="['/paper-collection-id', paperCollectionId.id, 'view']">{{ paperCollectionId.id }}</a></td>
                    <td class="text-right">
                        <div class="btn-group">
                            <button type="submit"
                                    [routerLink]="['/paper-collection-id', paperCollectionId.id, 'view']"
                                    class="btn btn-info btn-sm">
                                <fa-icon icon="eye"></fa-icon>
                                <span class="d-none d-md-inline" jhiTranslate="entity.action.view">View</span>
                            </button>

                            <button type="submit"
                                    [routerLink]="['/paper-collection-id', paperCollectionId.id, 'edit']"
                                    class="btn btn-primary btn-sm">
                                <fa-icon icon="pencil-alt"></fa-icon>
                                <span class="d-none d-md-inline" jhiTranslate="entity.action.edit">Edit</span>
                            </button>

                            <button type="submit" (click)="delete(paperCollectionId)"
                                    class="btn btn-danger btn-sm">
                                <fa-icon icon="times"></fa-icon>
                                <span class="d-none d-md-inline" jhiTranslate="entity.action.delete">Delete</span>
                            </button>
                        </div>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>

// jHipsterHeroku/src/main/webapp/app/entities/paper-collection-id/paper-collection-id.tsx
import React, { useState, useEffect } from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Col, Row, Table } from 'reactstrap';
import { Translate, ICrudGetAllAction } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getEntities } from './paper-collection-id.reducer';
import { IPaperCollectionId } from 'app/shared/model/paper-collection-id.model';
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';

export interface IPaperCollectionIdProps extends StateProps, DispatchProps, RouteComponentProps<{ url: string }> {}

export const PaperCollectionId = (props: IPaperCollectionIdProps) => {
  useEffect(() => {
    props.getEntities();
  }, []);

  const { paperCollectionIdList, match, loading } = props;
  return (
    <div>
      <h2 id="paper-collection-id-heading">
        <Translate contentKey="referenceManagementMonolithApp.paperCollectionId.home.title">Paper Collection Ids</Translate>
        <Link to={`${match.url}/new`} className="btn btn-primary float-right jh-create-entity" id="jh-create-entity">
          <FontAwesomeIcon icon="plus" />
          &nbsp;
          <Translate contentKey="referenceManagementMonolithApp.paperCollectionId.home.createLabel">
            Create new Paper Collection Id
          </Translate>
        </Link>
      </h2>
      <div className="table-responsive">
        {paperCollectionIdList && paperCollectionIdList.length > 0 ? (
          <Table responsive>
            <thead>
              <tr>
                <th>
                  <Translate contentKey="global.field.id">ID</Translate>
                </th>
                <th />
              </tr>
            </thead>
            <tbody>
              {paperCollectionIdList.map((paperCollectionId, i) => (
                <tr key={`entity-${i}`}>
                  <td>
                    <Button tag={Link} to={`${match.url}/${paperCollectionId.id}`} color="link" size="sm">
                      {paperCollectionId.id}
                    </Button>
                  </td>
                  <td className="text-right">
                    <div className="btn-group flex-btn-group-container">
                      <Button tag={Link} to={`${match.url}/${paperCollectionId.id}`} color="info" size="sm">
                        <FontAwesomeIcon icon="eye" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.view">View</Translate>
                        </span>
                      </Button>
                      <Button tag={Link} to={`${match.url}/${paperCollectionId.id}/edit`} color="primary" size="sm">
                        <FontAwesomeIcon icon="pencil-alt" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.edit">Edit</Translate>
                        </span>
                      </Button>
                      <Button tag={Link} to={`${match.url}/${paperCollectionId.id}/delete`} color="danger" size="sm">
                        <FontAwesomeIcon icon="trash" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.delete">Delete</Translate>
                        </span>
                      </Button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </Table>
        ) : (
          !loading && (
            <div className="alert alert-warning">
              <Translate contentKey="referenceManagementMonolithApp.paperCollectionId.home.notFound">
                No Paper Collection Ids found
              </Translate>
            </div>
          )
        )}
      </div>
    </div>
  );
};

const mapStateToProps = ({ paperCollectionId }: IRootState) => ({
  paperCollectionIdList: paperCollectionId.entities,
  loading: paperCollectionId.loading,
});

const mapDispatchToProps = {
  getEntities,
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(mapStateToProps, mapDispatchToProps)(PaperCollectionId);
