// jHipsterMicroservices/gateway/src/main/webapp/app/entities/ReferenceManagementContext/paper-collection-id/paper-collection-id-delete-dialog.component.ts
import { Component } from '@angular/core';
import { NgbActiveModal } from '@ng-bootstrap/ng-bootstrap';
import { JhiEventManager } from 'ng-jhipster';

import { IPaperCollectionId } from 'app/shared/model/ReferenceManagementContext/paper-collection-id.model';
import { PaperCollectionIdService } from './paper-collection-id.service';

@Component({
  templateUrl: './paper-collection-id-delete-dialog.component.html',
})
export class PaperCollectionIdDeleteDialogComponent {
  paperCollectionId?: IPaperCollectionId;

  constructor(
    protected paperCollectionIdService: PaperCollectionIdService,
    public activeModal: NgbActiveModal,
    protected eventManager: JhiEventManager
  ) {}

  cancel(): void {
    this.activeModal.dismiss();
  }

  confirmDelete(id: number): void {
    this.paperCollectionIdService.delete(id).subscribe(() => {
      this.eventManager.broadcast('paperCollectionIdListModification');
      this.activeModal.close();
    });
  }
}

<form *ngIf="paperCollectionId" name="deleteForm" (ngSubmit)="confirmDelete(paperCollectionId?.id!)">
    <div class="modal-header">
        <h4 class="modal-title" jhiTranslate="entity.delete.title">Confirm delete operation</h4>

        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"
                (click)="cancel()">&times;</button>
    </div>

    <div class="modal-body">
        <jhi-alert-error></jhi-alert-error>

        <p id="jhi-delete-paperCollectionId-heading" jhiTranslate="gatewayApp.referenceManagementContextPaperCollectionId.delete.question" [translateValues]="{ id: paperCollectionId.id }">Are you sure you want to delete this Paper Collection Id?</p>
    </div>

    <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal" (click)="cancel()">
            <fa-icon icon="ban"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
        </button>

        <button id="jhi-confirm-delete-paperCollectionId" type="submit" class="btn btn-danger">
            <fa-icon icon="times"></fa-icon>&nbsp;<span jhiTranslate="entity.action.delete">Delete</span>
        </button>
    </div>
</form>

// jHipsterHeroku/src/main/webapp/app/entities/paper-collection-id/paper-collection-id-delete-dialog.tsx
import React, { useEffect } from 'react';
import { connect } from 'react-redux';
import { RouteComponentProps } from 'react-router-dom';
import { Modal, ModalHeader, ModalBody, ModalFooter, Button } from 'reactstrap';
import { Translate, ICrudGetAction, ICrudDeleteAction } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IPaperCollectionId } from 'app/shared/model/paper-collection-id.model';
import { IRootState } from 'app/shared/reducers';
import { getEntity, deleteEntity } from './paper-collection-id.reducer';

export interface IPaperCollectionIdDeleteDialogProps extends StateProps, DispatchProps, RouteComponentProps<{ id: string }> {}

export const PaperCollectionIdDeleteDialog = (props: IPaperCollectionIdDeleteDialogProps) => {
  useEffect(() => {
    props.getEntity(props.match.params.id);
  }, []);

  const handleClose = () => {
    props.history.push('/paper-collection-id');
  };

  useEffect(() => {
    if (props.updateSuccess) {
      handleClose();
    }
  }, [props.updateSuccess]);

  const confirmDelete = () => {
    props.deleteEntity(props.paperCollectionIdEntity.id);
  };

  const { paperCollectionIdEntity } = props;
  return (
    <Modal isOpen toggle={handleClose}>
      <ModalHeader toggle={handleClose}>
        <Translate contentKey="entity.delete.title">Confirm delete operation</Translate>
      </ModalHeader>
      <ModalBody id="referenceManagementMonolithApp.paperCollectionId.delete.question">
        <Translate
          contentKey="referenceManagementMonolithApp.paperCollectionId.delete.question"
          interpolate={{ id: paperCollectionIdEntity.id }}
        >
          Are you sure you want to delete this PaperCollectionId?
        </Translate>
      </ModalBody>
      <ModalFooter>
        <Button color="secondary" onClick={handleClose}>
          <FontAwesomeIcon icon="ban" />
          &nbsp;
          <Translate contentKey="entity.action.cancel">Cancel</Translate>
        </Button>
        <Button id="jhi-confirm-delete-paperCollectionId" color="danger" onClick={confirmDelete}>
          <FontAwesomeIcon icon="trash" />
          &nbsp;
          <Translate contentKey="entity.action.delete">Delete</Translate>
        </Button>
      </ModalFooter>
    </Modal>
  );
};

const mapStateToProps = ({ paperCollectionId }: IRootState) => ({
  paperCollectionIdEntity: paperCollectionId.entity,
  updateSuccess: paperCollectionId.updateSuccess,
});

const mapDispatchToProps = { getEntity, deleteEntity };

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(mapStateToProps, mapDispatchToProps)(PaperCollectionIdDeleteDialog);
