// jHipsterHeroku/src/main/webapp/app/entities/paper-item-id/paper-item-id.tsx
import React, { useState, useEffect } from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Col, Row, Table } from 'reactstrap';
import { Translate, ICrudGetAllAction } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getEntities } from './paper-item-id.reducer';
import { IPaperItemId } from 'app/shared/model/paper-item-id.model';
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';

export interface IPaperItemIdProps extends StateProps, DispatchProps, RouteComponentProps<{ url: string }> {}

export const PaperItemId = (props: IPaperItemIdProps) => {
  useEffect(() => {
    props.getEntities();
  }, []);

  const { paperItemIdList, match, loading } = props;
  return (
    <div>
      <h2 id="paper-item-id-heading">
        <Translate contentKey="referenceManagementMonolithApp.paperItemId.home.title">Paper Item Ids</Translate>
        <Link to={`${match.url}/new`} className="btn btn-primary float-right jh-create-entity" id="jh-create-entity">
          <FontAwesomeIcon icon="plus" />
          &nbsp;
          <Translate contentKey="referenceManagementMonolithApp.paperItemId.home.createLabel">Create new Paper Item Id</Translate>
        </Link>
      </h2>
      <div className="table-responsive">
        {paperItemIdList && paperItemIdList.length > 0 ? (
          <Table responsive>
            <thead>
              <tr>
                <th>
                  <Translate contentKey="global.field.id">ID</Translate>
                </th>
                <th />
              </tr>
            </thead>
            <tbody>
              {paperItemIdList.map((paperItemId, i) => (
                <tr key={`entity-${i}`}>
                  <td>
                    <Button tag={Link} to={`${match.url}/${paperItemId.id}`} color="link" size="sm">
                      {paperItemId.id}
                    </Button>
                  </td>
                  <td className="text-right">
                    <div className="btn-group flex-btn-group-container">
                      <Button tag={Link} to={`${match.url}/${paperItemId.id}`} color="info" size="sm">
                        <FontAwesomeIcon icon="eye" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.view">View</Translate>
                        </span>
                      </Button>
                      <Button tag={Link} to={`${match.url}/${paperItemId.id}/edit`} color="primary" size="sm">
                        <FontAwesomeIcon icon="pencil-alt" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.edit">Edit</Translate>
                        </span>
                      </Button>
                      <Button tag={Link} to={`${match.url}/${paperItemId.id}/delete`} color="danger" size="sm">
                        <FontAwesomeIcon icon="trash" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.delete">Delete</Translate>
                        </span>
                      </Button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </Table>
        ) : (
          !loading && (
            <div className="alert alert-warning">
              <Translate contentKey="referenceManagementMonolithApp.paperItemId.home.notFound">No Paper Item Ids found</Translate>
            </div>
          )
        )}
      </div>
    </div>
  );
};

const mapStateToProps = ({ paperItemId }: IRootState) => ({
  paperItemIdList: paperItemId.entities,
  loading: paperItemId.loading,
});

const mapDispatchToProps = {
  getEntities,
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(mapStateToProps, mapDispatchToProps)(PaperItemId);

// jHipsterMicroservices/gateway/src/main/webapp/app/entities/ReferenceManagementContext/paper-item-id/paper-item-id.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
import { Subscription } from 'rxjs';
import { JhiEventManager } from 'ng-jhipster';
import { NgbModal } from '@ng-bootstrap/ng-bootstrap';

import { IPaperItemId } from 'app/shared/model/ReferenceManagementContext/paper-item-id.model';
import { PaperItemIdService } from './paper-item-id.service';
import { PaperItemIdDeleteDialogComponent } from './paper-item-id-delete-dialog.component';

@Component({
  selector: 'jhi-paper-item-id',
  templateUrl: './paper-item-id.component.html',
})
export class PaperItemIdComponent implements OnInit, OnDestroy {
  paperItemIds?: IPaperItemId[];
  eventSubscriber?: Subscription;

  constructor(
    protected paperItemIdService: PaperItemIdService,
    protected eventManager: JhiEventManager,
    protected modalService: NgbModal
  ) {}

  loadAll(): void {
    this.paperItemIdService.query().subscribe((res: HttpResponse<IPaperItemId[]>) => (this.paperItemIds = res.body || []));
  }

  ngOnInit(): void {
    this.loadAll();
    this.registerChangeInPaperItemIds();
  }

  ngOnDestroy(): void {
    if (this.eventSubscriber) {
      this.eventManager.destroy(this.eventSubscriber);
    }
  }

  trackId(index: number, item: IPaperItemId): number {
    // eslint-disable-next-line @typescript-eslint/no-unnecessary-type-assertion
    return item.id!;
  }

  registerChangeInPaperItemIds(): void {
    this.eventSubscriber = this.eventManager.subscribe('paperItemIdListModification', () => this.loadAll());
  }

  delete(paperItemId: IPaperItemId): void {
    const modalRef = this.modalService.open(PaperItemIdDeleteDialogComponent, { size: 'lg', backdrop: 'static' });
    modalRef.componentInstance.paperItemId = paperItemId;
  }
}

<div>
    <h2 id="page-heading">
        <span jhiTranslate="gatewayApp.referenceManagementContextPaperItemId.home.title">Paper Item Ids</span>

        <button id="jh-create-entity" class="btn btn-primary float-right jh-create-entity create-paper-item-id" [routerLink]="['/paper-item-id/new']">
            <fa-icon icon="plus"></fa-icon>
            <span  jhiTranslate="gatewayApp.referenceManagementContextPaperItemId.home.createLabel">
            Create a new Paper Item Id
            </span>
        </button>
    </h2>

    <jhi-alert-error></jhi-alert-error>

    <jhi-alert></jhi-alert>

    <div class="alert alert-warning" id="no-result" *ngIf="paperItemIds?.length === 0">
        <span jhiTranslate="gatewayApp.referenceManagementContextPaperItemId.home.notFound">No paperItemIds found</span>
    </div>

    <div class="table-responsive" id="entities" *ngIf="paperItemIds && paperItemIds.length > 0">
        <table class="table table-striped" aria-describedby="page-heading">
            <thead>
                <tr>
                    <th scope="col" ><span jhiTranslate="global.field.id">ID</span></th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                <tr *ngFor="let paperItemId of paperItemIds ;trackBy: trackId">
                    <td><a [routerLink]="['/paper-item-id', paperItemId.id, 'view']">{{ paperItemId.id }}</a></td>
                    <td class="text-right">
                        <div class="btn-group">
                            <button type="submit"
                                    [routerLink]="['/paper-item-id', paperItemId.id, 'view']"
                                    class="btn btn-info btn-sm">
                                <fa-icon icon="eye"></fa-icon>
                                <span class="d-none d-md-inline" jhiTranslate="entity.action.view">View</span>
                            </button>

                            <button type="submit"
                                    [routerLink]="['/paper-item-id', paperItemId.id, 'edit']"
                                    class="btn btn-primary btn-sm">
                                <fa-icon icon="pencil-alt"></fa-icon>
                                <span class="d-none d-md-inline" jhiTranslate="entity.action.edit">Edit</span>
                            </button>

                            <button type="submit" (click)="delete(paperItemId)"
                                    class="btn btn-danger btn-sm">
                                <fa-icon icon="times"></fa-icon>
                                <span class="d-none d-md-inline" jhiTranslate="entity.action.delete">Delete</span>
                            </button>
                        </div>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
