// jHipsterMicroservices/gateway/src/main/webapp/app/entities/ReferenceManagementContext/paper-collection/paper-collection.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
import { Subscription } from 'rxjs';
import { JhiEventManager } from 'ng-jhipster';
import { NgbModal } from '@ng-bootstrap/ng-bootstrap';

import { IPaperCollection } from 'app/shared/model/ReferenceManagementContext/paper-collection.model';
import { PaperCollectionService } from './paper-collection.service';
import { PaperCollectionDeleteDialogComponent } from './paper-collection-delete-dialog.component';

@Component({
  selector: 'jhi-paper-collection',
  templateUrl: './paper-collection.component.html',
})
export class PaperCollectionComponent implements OnInit, OnDestroy {
  paperCollections?: IPaperCollection[];
  eventSubscriber?: Subscription;

  constructor(
    protected paperCollectionService: PaperCollectionService,
    protected eventManager: JhiEventManager,
    protected modalService: NgbModal
  ) {}

  loadAll(): void {
    this.paperCollectionService.query().subscribe((res: HttpResponse<IPaperCollection[]>) => (this.paperCollections = res.body || []));
  }

  ngOnInit(): void {
    this.loadAll();
    this.registerChangeInPaperCollections();
  }

  ngOnDestroy(): void {
    if (this.eventSubscriber) {
      this.eventManager.destroy(this.eventSubscriber);
    }
  }

  trackId(index: number, item: IPaperCollection): number {
    // eslint-disable-next-line @typescript-eslint/no-unnecessary-type-assertion
    return item.id!;
  }

  registerChangeInPaperCollections(): void {
    this.eventSubscriber = this.eventManager.subscribe('paperCollectionListModification', () => this.loadAll());
  }

  delete(paperCollection: IPaperCollection): void {
    const modalRef = this.modalService.open(PaperCollectionDeleteDialogComponent, { size: 'lg', backdrop: 'static' });
    modalRef.componentInstance.paperCollection = paperCollection;
  }
}

<div>
    <h2 id="page-heading">
        <span jhiTranslate="gatewayApp.referenceManagementContextPaperCollection.home.title">Paper Collections</span>

        <button id="jh-create-entity" class="btn btn-primary float-right jh-create-entity create-paper-collection" [routerLink]="['/paper-collection/new']">
            <fa-icon icon="plus"></fa-icon>
            <span  jhiTranslate="gatewayApp.referenceManagementContextPaperCollection.home.createLabel">
            Create a new Paper Collection
            </span>
        </button>
    </h2>

    <jhi-alert-error></jhi-alert-error>

    <jhi-alert></jhi-alert>

    <div class="alert alert-warning" id="no-result" *ngIf="paperCollections?.length === 0">
        <span jhiTranslate="gatewayApp.referenceManagementContextPaperCollection.home.notFound">No paperCollections found</span>
    </div>

    <div class="table-responsive" id="entities" *ngIf="paperCollections && paperCollections.length > 0">
        <table class="table table-striped" aria-describedby="page-heading">
            <thead>
                <tr>
                    <th scope="col" ><span jhiTranslate="global.field.id">ID</span></th>
                    <th scope="col" ><span jhiTranslate="gatewayApp.referenceManagementContextPaperCollection.paperCollectionId">Paper Collection Id</span></th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                <tr *ngFor="let paperCollection of paperCollections ;trackBy: trackId">
                    <td><a [routerLink]="['/paper-collection', paperCollection.id, 'view']">{{ paperCollection.id }}</a></td>
                    <td>
                        <div *ngIf="paperCollection.paperCollectionIdId">
                            <a [routerLink]="['/paper-collection-id', paperCollection.paperCollectionIdId , 'view']" >{{ paperCollection.paperCollectionIdId }}</a>
                        </div>
                    </td>
                    <td class="text-right">
                        <div class="btn-group">
                            <button type="submit"
                                    [routerLink]="['/paper-collection', paperCollection.id, 'view']"
                                    class="btn btn-info btn-sm">
                                <fa-icon icon="eye"></fa-icon>
                                <span class="d-none d-md-inline" jhiTranslate="entity.action.view">View</span>
                            </button>

                            <button type="submit"
                                    [routerLink]="['/paper-collection', paperCollection.id, 'edit']"
                                    class="btn btn-primary btn-sm">
                                <fa-icon icon="pencil-alt"></fa-icon>
                                <span class="d-none d-md-inline" jhiTranslate="entity.action.edit">Edit</span>
                            </button>

                            <button type="submit" (click)="delete(paperCollection)"
                                    class="btn btn-danger btn-sm">
                                <fa-icon icon="times"></fa-icon>
                                <span class="d-none d-md-inline" jhiTranslate="entity.action.delete">Delete</span>
                            </button>
                        </div>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>

// jHipsterMonolith/src/main/webapp/app/entities/paper-collection/paper-collection.tsx
import React, { useState, useEffect } from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Col, Row, Table } from 'reactstrap';
import { Translate, ICrudGetAllAction } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getEntities } from './paper-collection.reducer';
import { IPaperCollection } from 'app/shared/model/paper-collection.model';
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';

export interface IPaperCollectionProps extends StateProps, DispatchProps, RouteComponentProps<{ url: string }> {}

export const PaperCollection = (props: IPaperCollectionProps) => {
  useEffect(() => {
    props.getEntities();
  }, []);

  const { paperCollectionList, match, loading } = props;
  return (
    <div>
      <h2 id="paper-collection-heading">
        <Translate contentKey="referenceManagementMonolithApp.paperCollection.home.title">Paper Collections</Translate>
        <Link to={`${match.url}/new`} className="btn btn-primary float-right jh-create-entity" id="jh-create-entity">
          <FontAwesomeIcon icon="plus" />
          &nbsp;
          <Translate contentKey="referenceManagementMonolithApp.paperCollection.home.createLabel">Create new Paper Collection</Translate>
        </Link>
      </h2>
      <div className="table-responsive">
        {paperCollectionList && paperCollectionList.length > 0 ? (
          <Table responsive>
            <thead>
              <tr>
                <th>
                  <Translate contentKey="global.field.id">ID</Translate>
                </th>
                <th>
                  <Translate contentKey="referenceManagementMonolithApp.paperCollection.paperCollectionId">Paper Collection Id</Translate>
                </th>
                <th />
              </tr>
            </thead>
            <tbody>
              {paperCollectionList.map((paperCollection, i) => (
                <tr key={`entity-${i}`}>
                  <td>
                    <Button tag={Link} to={`${match.url}/${paperCollection.id}`} color="link" size="sm">
                      {paperCollection.id}
                    </Button>
                  </td>
                  <td>
                    {paperCollection.paperCollectionIdId ? (
                      <Link to={`paper-collection-id/${paperCollection.paperCollectionIdId}`}>{paperCollection.paperCollectionIdId}</Link>
                    ) : (
                      ''
                    )}
                  </td>
                  <td className="text-right">
                    <div className="btn-group flex-btn-group-container">
                      <Button tag={Link} to={`${match.url}/${paperCollection.id}`} color="info" size="sm">
                        <FontAwesomeIcon icon="eye" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.view">View</Translate>
                        </span>
                      </Button>
                      <Button tag={Link} to={`${match.url}/${paperCollection.id}/edit`} color="primary" size="sm">
                        <FontAwesomeIcon icon="pencil-alt" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.edit">Edit</Translate>
                        </span>
                      </Button>
                      <Button tag={Link} to={`${match.url}/${paperCollection.id}/delete`} color="danger" size="sm">
                        <FontAwesomeIcon icon="trash" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.delete">Delete</Translate>
                        </span>
                      </Button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </Table>
        ) : (
          !loading && (
            <div className="alert alert-warning">
              <Translate contentKey="referenceManagementMonolithApp.paperCollection.home.notFound">No Paper Collections found</Translate>
            </div>
          )
        )}
      </div>
    </div>
  );
};

const mapStateToProps = ({ paperCollection }: IRootState) => ({
  paperCollectionList: paperCollection.entities,
  loading: paperCollection.loading,
});

const mapDispatchToProps = {
  getEntities,
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(mapStateToProps, mapDispatchToProps)(PaperCollection);
