// jHipsterHeroku/src/main/webapp/app/entities/paper-collection/paper-collection-detail.tsx
import React, { useEffect } from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col } from 'reactstrap';
import { Translate, ICrudGetAction } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getEntity } from './paper-collection.reducer';
import { IPaperCollection } from 'app/shared/model/paper-collection.model';
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';

export interface IPaperCollectionDetailProps extends StateProps, DispatchProps, RouteComponentProps<{ id: string }> {}

export const PaperCollectionDetail = (props: IPaperCollectionDetailProps) => {
  useEffect(() => {
    props.getEntity(props.match.params.id);
  }, []);

  const { paperCollectionEntity } = props;
  return (
    <Row>
      <Col md="8">
        <h2>
          <Translate contentKey="referenceManagementMonolithApp.paperCollection.detail.title">PaperCollection</Translate> [
          <b>{paperCollectionEntity.id}</b>]
        </h2>
        <dl className="jh-entity-details">
          <dt>
            <Translate contentKey="referenceManagementMonolithApp.paperCollection.paperCollectionId">Paper Collection Id</Translate>
          </dt>
          <dd>{paperCollectionEntity.paperCollectionIdId ? paperCollectionEntity.paperCollectionIdId : ''}</dd>
        </dl>
        <Button tag={Link} to="/paper-collection" replace color="info">
          <FontAwesomeIcon icon="arrow-left" />{' '}
          <span className="d-none d-md-inline">
            <Translate contentKey="entity.action.back">Back</Translate>
          </span>
        </Button>
        &nbsp;
        <Button tag={Link} to={`/paper-collection/${paperCollectionEntity.id}/edit`} replace color="primary">
          <FontAwesomeIcon icon="pencil-alt" />{' '}
          <span className="d-none d-md-inline">
            <Translate contentKey="entity.action.edit">Edit</Translate>
          </span>
        </Button>
      </Col>
    </Row>
  );
};

const mapStateToProps = ({ paperCollection }: IRootState) => ({
  paperCollectionEntity: paperCollection.entity,
});

const mapDispatchToProps = { getEntity };

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(mapStateToProps, mapDispatchToProps)(PaperCollectionDetail);

// jHipsterMicroservices/gateway/src/main/webapp/app/entities/ReferenceManagementContext/paper-collection/paper-collection-detail.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';

import { IPaperCollection } from 'app/shared/model/ReferenceManagementContext/paper-collection.model';

@Component({
  selector: 'jhi-paper-collection-detail',
  templateUrl: './paper-collection-detail.component.html',
})
export class PaperCollectionDetailComponent implements OnInit {
  paperCollection: IPaperCollection | null = null;

  constructor(protected activatedRoute: ActivatedRoute) {}

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ paperCollection }) => (this.paperCollection = paperCollection));
  }

  previousState(): void {
    window.history.back();
  }
}

<div class="row justify-content-center">
    <div class="col-8">
        <div *ngIf="paperCollection">
            <h2><span jhiTranslate="gatewayApp.referenceManagementContextPaperCollection.detail.title">Paper Collection</span> {{ paperCollection.id }}</h2>

            <hr>

            <jhi-alert-error></jhi-alert-error>

            <dl class="row-md jh-entity-details">
                <dt><span jhiTranslate="gatewayApp.referenceManagementContextPaperCollection.paperCollectionId">Paper Collection Id</span></dt>
                <dd>
                    <div *ngIf="paperCollection.paperCollectionIdId">
                        <a [routerLink]="['/paper-collection-id', paperCollection.paperCollectionIdId, 'view']">{{ paperCollection.paperCollectionIdId }}</a>
                    </div>
                </dd>
            </dl>

            <button type="submit"
                    (click)="previousState()"
                    class="btn btn-info">
                <fa-icon icon="arrow-left"></fa-icon>&nbsp;<span jhiTranslate="entity.action.back">Back</span>
            </button>

            <button type="button"
                    [routerLink]="['/paper-collection', paperCollection.id, 'edit']"
                    class="btn btn-primary">
                <fa-icon icon="pencil-alt"></fa-icon>&nbsp;<span jhiTranslate="entity.action.edit">Edit</span>
            </button>
        </div>
    </div>
</div>
