// jHipsterMicroservices/gateway/src/main/webapp/app/entities/ReferenceManagementContext/paper-item-id/paper-item-id-delete-dialog.component.ts
import { Component } from '@angular/core';
import { NgbActiveModal } from '@ng-bootstrap/ng-bootstrap';
import { JhiEventManager } from 'ng-jhipster';

import { IPaperItemId } from 'app/shared/model/ReferenceManagementContext/paper-item-id.model';
import { PaperItemIdService } from './paper-item-id.service';

@Component({
  templateUrl: './paper-item-id-delete-dialog.component.html',
})
export class PaperItemIdDeleteDialogComponent {
  paperItemId?: IPaperItemId;

  constructor(
    protected paperItemIdService: PaperItemIdService,
    public activeModal: NgbActiveModal,
    protected eventManager: JhiEventManager
  ) {}

  cancel(): void {
    this.activeModal.dismiss();
  }

  confirmDelete(id: number): void {
    this.paperItemIdService.delete(id).subscribe(() => {
      this.eventManager.broadcast('paperItemIdListModification');
      this.activeModal.close();
    });
  }
}

<form *ngIf="paperItemId" name="deleteForm" (ngSubmit)="confirmDelete(paperItemId?.id!)">
    <div class="modal-header">
        <h4 class="modal-title" jhiTranslate="entity.delete.title">Confirm delete operation</h4>

        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"
                (click)="cancel()">&times;</button>
    </div>

    <div class="modal-body">
        <jhi-alert-error></jhi-alert-error>

        <p id="jhi-delete-paperItemId-heading" jhiTranslate="gatewayApp.referenceManagementContextPaperItemId.delete.question" [translateValues]="{ id: paperItemId.id }">Are you sure you want to delete this Paper Item Id?</p>
    </div>

    <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal" (click)="cancel()">
            <fa-icon icon="ban"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
        </button>

        <button id="jhi-confirm-delete-paperItemId" type="submit" class="btn btn-danger">
            <fa-icon icon="times"></fa-icon>&nbsp;<span jhiTranslate="entity.action.delete">Delete</span>
        </button>
    </div>
</form>

// jHipsterHeroku/src/main/webapp/app/entities/paper-item-id/paper-item-id-delete-dialog.tsx
import React, { useEffect } from 'react';
import { connect } from 'react-redux';
import { RouteComponentProps } from 'react-router-dom';
import { Modal, ModalHeader, ModalBody, ModalFooter, Button } from 'reactstrap';
import { Translate, ICrudGetAction, ICrudDeleteAction } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IPaperItemId } from 'app/shared/model/paper-item-id.model';
import { IRootState } from 'app/shared/reducers';
import { getEntity, deleteEntity } from './paper-item-id.reducer';

export interface IPaperItemIdDeleteDialogProps extends StateProps, DispatchProps, RouteComponentProps<{ id: string }> {}

export const PaperItemIdDeleteDialog = (props: IPaperItemIdDeleteDialogProps) => {
  useEffect(() => {
    props.getEntity(props.match.params.id);
  }, []);

  const handleClose = () => {
    props.history.push('/paper-item-id');
  };

  useEffect(() => {
    if (props.updateSuccess) {
      handleClose();
    }
  }, [props.updateSuccess]);

  const confirmDelete = () => {
    props.deleteEntity(props.paperItemIdEntity.id);
  };

  const { paperItemIdEntity } = props;
  return (
    <Modal isOpen toggle={handleClose}>
      <ModalHeader toggle={handleClose}>
        <Translate contentKey="entity.delete.title">Confirm delete operation</Translate>
      </ModalHeader>
      <ModalBody id="referenceManagementMonolithApp.paperItemId.delete.question">
        <Translate contentKey="referenceManagementMonolithApp.paperItemId.delete.question" interpolate={{ id: paperItemIdEntity.id }}>
          Are you sure you want to delete this PaperItemId?
        </Translate>
      </ModalBody>
      <ModalFooter>
        <Button color="secondary" onClick={handleClose}>
          <FontAwesomeIcon icon="ban" />
          &nbsp;
          <Translate contentKey="entity.action.cancel">Cancel</Translate>
        </Button>
        <Button id="jhi-confirm-delete-paperItemId" color="danger" onClick={confirmDelete}>
          <FontAwesomeIcon icon="trash" />
          &nbsp;
          <Translate contentKey="entity.action.delete">Delete</Translate>
        </Button>
      </ModalFooter>
    </Modal>
  );
};

const mapStateToProps = ({ paperItemId }: IRootState) => ({
  paperItemIdEntity: paperItemId.entity,
  updateSuccess: paperItemId.updateSuccess,
});

const mapDispatchToProps = { getEntity, deleteEntity };

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(mapStateToProps, mapDispatchToProps)(PaperItemIdDeleteDialog);
