// jHipsterMonolith/src/main/webapp/app/entities/paper-item/paper-item.tsx
import React, { useState, useEffect } from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Col, Row, Table } from 'reactstrap';
import { Translate, ICrudGetAllAction } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getEntities } from './paper-item.reducer';
import { IPaperItem } from 'app/shared/model/paper-item.model';
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';

export interface IPaperItemProps extends StateProps, DispatchProps, RouteComponentProps<{ url: string }> {}

export const PaperItem = (props: IPaperItemProps) => {
  useEffect(() => {
    props.getEntities();
  }, []);

  const { paperItemList, match, loading } = props;
  return (
    <div>
      <h2 id="paper-item-heading">
        <Translate contentKey="referenceManagementMonolithApp.paperItem.home.title">Paper Items</Translate>
        <Link to={`${match.url}/new`} className="btn btn-primary float-right jh-create-entity" id="jh-create-entity">
          <FontAwesomeIcon icon="plus" />
          &nbsp;
          <Translate contentKey="referenceManagementMonolithApp.paperItem.home.createLabel">Create new Paper Item</Translate>
        </Link>
      </h2>
      <div className="table-responsive">
        {paperItemList && paperItemList.length > 0 ? (
          <Table responsive>
            <thead>
              <tr>
                <th>
                  <Translate contentKey="global.field.id">ID</Translate>
                </th>
                <th>
                  <Translate contentKey="referenceManagementMonolithApp.paperItem.title">Title</Translate>
                </th>
                <th>
                  <Translate contentKey="referenceManagementMonolithApp.paperItem.authors">Authors</Translate>
                </th>
                <th>
                  <Translate contentKey="referenceManagementMonolithApp.paperItem.venue">Venue</Translate>
                </th>
                <th>
                  <Translate contentKey="referenceManagementMonolithApp.paperItem.paperitemId">Paperitem Id</Translate>
                </th>
                <th>
                  <Translate contentKey="referenceManagementMonolithApp.paperItem.paperCollection">Paper Collection</Translate>
                </th>
                <th />
              </tr>
            </thead>
            <tbody>
              {paperItemList.map((paperItem, i) => (
                <tr key={`entity-${i}`}>
                  <td>
                    <Button tag={Link} to={`${match.url}/${paperItem.id}`} color="link" size="sm">
                      {paperItem.id}
                    </Button>
                  </td>
                  <td>{paperItem.title}</td>
                  <td>{paperItem.authors}</td>
                  <td>{paperItem.venue}</td>
                  <td>
                    {paperItem.paperitemIdId ? <Link to={`paper-item-id/${paperItem.paperitemIdId}`}>{paperItem.paperitemIdId}</Link> : ''}
                  </td>
                  <td>
                    {paperItem.paperCollectionId ? (
                      <Link to={`paper-collection/${paperItem.paperCollectionId}`}>{paperItem.paperCollectionId}</Link>
                    ) : (
                      ''
                    )}
                  </td>
                  <td className="text-right">
                    <div className="btn-group flex-btn-group-container">
                      <Button tag={Link} to={`${match.url}/${paperItem.id}`} color="info" size="sm">
                        <FontAwesomeIcon icon="eye" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.view">View</Translate>
                        </span>
                      </Button>
                      <Button tag={Link} to={`${match.url}/${paperItem.id}/edit`} color="primary" size="sm">
                        <FontAwesomeIcon icon="pencil-alt" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.edit">Edit</Translate>
                        </span>
                      </Button>
                      <Button tag={Link} to={`${match.url}/${paperItem.id}/delete`} color="danger" size="sm">
                        <FontAwesomeIcon icon="trash" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.delete">Delete</Translate>
                        </span>
                      </Button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </Table>
        ) : (
          !loading && (
            <div className="alert alert-warning">
              <Translate contentKey="referenceManagementMonolithApp.paperItem.home.notFound">No Paper Items found</Translate>
            </div>
          )
        )}
      </div>
    </div>
  );
};

const mapStateToProps = ({ paperItem }: IRootState) => ({
  paperItemList: paperItem.entities,
  loading: paperItem.loading,
});

const mapDispatchToProps = {
  getEntities,
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(mapStateToProps, mapDispatchToProps)(PaperItem);

// jHipsterMicroservices/gateway/src/main/webapp/app/entities/ReferenceManagementContext/paper-item/paper-item.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
import { Subscription } from 'rxjs';
import { JhiEventManager } from 'ng-jhipster';
import { NgbModal } from '@ng-bootstrap/ng-bootstrap';

import { IPaperItem } from 'app/shared/model/ReferenceManagementContext/paper-item.model';
import { PaperItemService } from './paper-item.service';
import { PaperItemDeleteDialogComponent } from './paper-item-delete-dialog.component';

@Component({
  selector: 'jhi-paper-item',
  templateUrl: './paper-item.component.html',
})
export class PaperItemComponent implements OnInit, OnDestroy {
  paperItems?: IPaperItem[];
  eventSubscriber?: Subscription;

  constructor(protected paperItemService: PaperItemService, protected eventManager: JhiEventManager, protected modalService: NgbModal) {}

  loadAll(): void {
    this.paperItemService.query().subscribe((res: HttpResponse<IPaperItem[]>) => (this.paperItems = res.body || []));
  }

  ngOnInit(): void {
    this.loadAll();
    this.registerChangeInPaperItems();
  }

  ngOnDestroy(): void {
    if (this.eventSubscriber) {
      this.eventManager.destroy(this.eventSubscriber);
    }
  }

  trackId(index: number, item: IPaperItem): number {
    // eslint-disable-next-line @typescript-eslint/no-unnecessary-type-assertion
    return item.id!;
  }

  registerChangeInPaperItems(): void {
    this.eventSubscriber = this.eventManager.subscribe('paperItemListModification', () => this.loadAll());
  }

  delete(paperItem: IPaperItem): void {
    const modalRef = this.modalService.open(PaperItemDeleteDialogComponent, { size: 'lg', backdrop: 'static' });
    modalRef.componentInstance.paperItem = paperItem;
  }
}

<div>
    <h2 id="page-heading">
        <span jhiTranslate="gatewayApp.referenceManagementContextPaperItem.home.title">Paper Items</span>

        <button id="jh-create-entity" class="btn btn-primary float-right jh-create-entity create-paper-item" [routerLink]="['/paper-item/new']">
            <fa-icon icon="plus"></fa-icon>
            <span  jhiTranslate="gatewayApp.referenceManagementContextPaperItem.home.createLabel">
            Create a new Paper Item
            </span>
        </button>
    </h2>

    <jhi-alert-error></jhi-alert-error>

    <jhi-alert></jhi-alert>

    <div class="alert alert-warning" id="no-result" *ngIf="paperItems?.length === 0">
        <span jhiTranslate="gatewayApp.referenceManagementContextPaperItem.home.notFound">No paperItems found</span>
    </div>

    <div class="table-responsive" id="entities" *ngIf="paperItems && paperItems.length > 0">
        <table class="table table-striped" aria-describedby="page-heading">
            <thead>
                <tr>
                    <th scope="col" ><span jhiTranslate="global.field.id">ID</span></th>
                    <th scope="col" ><span jhiTranslate="gatewayApp.referenceManagementContextPaperItem.title">Title</span></th>
                    <th scope="col" ><span jhiTranslate="gatewayApp.referenceManagementContextPaperItem.authors">Authors</span></th>
                    <th scope="col" ><span jhiTranslate="gatewayApp.referenceManagementContextPaperItem.venue">Venue</span></th>
                    <th scope="col" ><span jhiTranslate="gatewayApp.referenceManagementContextPaperItem.paperitemId">Paperitem Id</span></th>
                    <th scope="col" ><span jhiTranslate="gatewayApp.referenceManagementContextPaperItem.paperCollection">Paper Collection</span></th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                <tr *ngFor="let paperItem of paperItems ;trackBy: trackId">
                    <td><a [routerLink]="['/paper-item', paperItem.id, 'view']">{{ paperItem.id }}</a></td>
                    <td>{{ paperItem.title }}</td>
                    <td>{{ paperItem.authors }}</td>
                    <td>{{ paperItem.venue }}</td>
                    <td>
                        <div *ngIf="paperItem.paperitemIdId">
                            <a [routerLink]="['/paper-item-id', paperItem.paperitemIdId , 'view']" >{{ paperItem.paperitemIdId }}</a>
                        </div>
                    </td>
                    <td>
                        <div *ngIf="paperItem.paperCollectionId">
                            <a [routerLink]="['/paper-collection', paperItem.paperCollectionId , 'view']" >{{ paperItem.paperCollectionId }}</a>
                        </div>
                    </td>
                    <td class="text-right">
                        <div class="btn-group">
                            <button type="submit"
                                    [routerLink]="['/paper-item', paperItem.id, 'view']"
                                    class="btn btn-info btn-sm">
                                <fa-icon icon="eye"></fa-icon>
                                <span class="d-none d-md-inline" jhiTranslate="entity.action.view">View</span>
                            </button>

                            <button type="submit"
                                    [routerLink]="['/paper-item', paperItem.id, 'edit']"
                                    class="btn btn-primary btn-sm">
                                <fa-icon icon="pencil-alt"></fa-icon>
                                <span class="d-none d-md-inline" jhiTranslate="entity.action.edit">Edit</span>
                            </button>

                            <button type="submit" (click)="delete(paperItem)"
                                    class="btn btn-danger btn-sm">
                                <fa-icon icon="times"></fa-icon>
                                <span class="d-none d-md-inline" jhiTranslate="entity.action.delete">Delete</span>
                            </button>
                        </div>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
